---
- name: Stop Apigee component {{ component }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ component }} stop'

- name: Remove Data Apigee component {{ component }}
  become: yes
  file:
    path: /opt/apigee/data/{{ component }}
    state: absent

- name: Remove Data Apigee component {{ component }}
  become: yes
  file:
    path: /opt/apigee/data/{{ component }}.d
    state: absent

- name: Restore Apigee component {{ component }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ component }} restore'

- name: Start Apigee component {{ component }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ component }} start'

- name: Wait for Apigee component {{ component }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ component }} wait_for_ready'
