---
- name: Stop Apigee Service {{ apigee_service }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ apigee_service }} stop'

- name: Remove Data Apigee Service {{ apigee_service }}
  become: yes
  file:
    path: /opt/apigee/data/{{ apigee_service }}
    state: absent

- name: Remove Data Apigee Service {{ apigee_service }}
  become: yes
  file:
    path: /opt/apigee/data/{{ apigee_service }}.d
    state: absent

- name: Restore Apigee Service {{ apigee_service }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ apigee_service }} restore'

- name: Start Apigee Service {{ apigee_service }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ apigee_service }} start'

- name: Wait for Apigee Service {{ apigee_service }}
  command: '/opt/apigee/apigee-service/bin/apigee-service {{ apigee_service }} wait_for_ready'
